### ISSUE TITLE
[1.7.10] - IDEA не цепляет ресурсы

### ISSUE THREAD

**Issue by RareScrap** [Ivasik78/KotlinWorkspace#1]
Ни sourceSets `{ main { output.resourcesDir = output.classesDir } }`, ни
`idea.module.inheritOutputDirs = true` не помогают. Как быть?

**Comment by Ivasik78** [comment]
![image](https://user-images.githubusercontent.com/9529993/83362977-643b7580-a39e-11ea-8d88-774b0fda8fe7.png)

**Comment by RareScrap** [comment]
Найс. Теперь `sourceSets { main { output.resourcesDir = output.classesDir } }` начал цеплять ресурсы. Спасибо!
